name: run-bot 24h
on:
  schedule:
    - cron: '0 */5 * * *'
  workflow_dispatch:
jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
      - run: pip install --no-cache-dir -r requirements.txt
      - env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        run: timeout 21000 python bot_cloud.py || true
